feat(bazel): support for terser v5 and 2020 in rollup_bundle rule (#215)
* feat(bazel): support for terser v5 and 2020 in rollup_bundle rule

Supports for terser v5 in the `ng_rollup_bundle` rule. currently
terser fails because there is a conflicting `--beautify` CLI flag
set by `@bazel/terser` and the `output` option. Instead, the
new `format` name should be used:

```
ERROR: Please only specify either output or format option, preferrably
format.
```

* fixup! feat(bazel): support for terser v5 and 2020 in rollup_bundle rule

Make output flavor more generic in comment