fix(bazel): spec bundling and app bundling breaking rxjs v6 testing code
RxJS v6 does not match any conditions so we end up bundling the
ES5 distribution which breaks surprisingly due to certain methods
being missed on e.g. `Observable`.

We fix this by just preferring the more up-to-date distribution.

```
     error: TypeError: observable2.logSubscribedFrame is not a function
          at ColdObservable2._subscribe (file:///usr/local/google/home/pgschwendtner/.cache/bazel/_bazel_pgschwendtner/84e2b91096f108a3ead3e72250add8ed/sandbox/linux-sandbox/285/execroot/angular/bazel-out/k8-fastbuild/bin/packages/router/node_modules/rxjs/src/internal/testing/ColdObservable.ts:26:32)
          at ColdObservable2.Observable2._trySubscribe (file:///usr/local/google/home/pgschwendtner/.cache/bazel/_bazel_pgschwendtner/84e2b91096f108a3ead3e72250add8ed/sandbox/linux-sandbox/285/execroot/angular/bazel-out/k8-fastbuild/bin/packages/router/node_modules/rxjs/src/internal/Observable.ts:239:6)
```