feat(ng-dev): support skipping version stamp in release stamp env
Some repositories like the `dev-infra` repository do not follow the
usual Angular SemVer versioning but still would like to use the shared
stamping script.

For these repositories, another option is added to the stamping command
that allows version info from being included. There needs to be a way
to disable this as otherwise stamping currently fails when it tries to
find/compute a SemVer version from the workspace `package.json`, causing
errors like:

```
TypeError: Invalid Version: 0.0.0-{SCM_HEAD_SHA}
```

This issue surfaces also on repositories which have a single `package.json`
that would be used for the stamping placeholder, plus the stamping script
itself..