ci: disable updating @angular-devkit/build-angular
Updating this leads to the Angular CLI build failing with `Error TS2322: Type 'Buffer' is not assignable to type 'Uint8Array'.` These errors occur only when building with Bazel.

Further investigation is necessary to identify the root cause.