fix(ng-dev): add `which` to direct dependencies (#2558)
The package depends on `which` but did not explicitly list it as a direct dependency, leading to build failures.

The following error was encountered during the build:
```
ERROR: <path-to-file>/BUILD.bazel:7:19: Bundling Javascript <path-to-file>/lib/main.ts [esbuild] failed: (Exit 1): _main_generated_esbuild_launcher.sh failed: error executing command
Error: Could not resolve "which"

    node_modules/@angular/ng-dev/utils/resolve-yarn-bin.js:10:18:
        import which from 'which';
                        ~~~~~~~
```