test: fix failures when test temporary directory does not exist (#185)
When running dev-infra tests in a new environment where the test
temporary directory does not exist, tests will fail because we
try to remove a directory that does not necessarily exist. This
prevents errors like the following:

```
47) move next into feature-freeze action should create pull requests and feature-freeze branch
  Message:
    Error: ENOENT: no such file or directory, stat '/private/var/tmp/_bazel_paul/3bab81b31c8f6213af73b4cc9d29338a/sandbox/darwin-sandbox/62/execroot/dev-infra/_tmp/68505bf391a8df2438b4fe69357a2bac/dev-infra'
  Stack:

```

PR Close #185